var adjective1 = prompt('Please enter an adjective');
var story = "<p>There once was a " + adjective1;
var pluralNoun = prompt('Please enter a plural noun');
var adjective2 = prompt('Please enter another adjective');
var noun1 = prompt('Please enter a noun');
var verb1 = prompt('Please enter a verb')
var adjective3 = prompt('Please enter another adjective');
var adjective4 = prompt('Please enter another adjective');
var person = prompt('Please enter a person');
var adjective5 = prompt('Please enter another adjective');
alert("Don't worry! You'er almost done!");
var person2 = prompt('Please enter a person');
var instrument = prompt('Please enter a musical instrument');
var adjective6 = prompt('Please enter another adjective');
var place1 = prompt('Please enter a place');
var adjective7 = prompt('Please enter another adjective');
var noun2 = prompt('Please enter another noun');
var verb2 = prompt('Please enter another verb');
var pluralNoun2 = prompt('Please enter another plural noun');
var noun4 = prompt('Please enter another noun');
var occupation = prompt('Please enter a type of occupation');
alert('All done. Ready for the story?');
story += ' Dragonborn who wanted to rid the world of ' + pluralNoun + '.';
story += ' At first, she was too ' + adjective2 + ' to take on the ' + pluralNoun + ' but she soon found a magic ' + noun1 + ' to help her on this quest.';
story += ' Not long after finding this ' + noun1 + ', she realized that she could use it to ' + verb1 + ' the ' + pluralNoun + '.';
story += ' But first, she needed to seek out the ' + adjective3 + ' and ' + adjective4 + ' ' + person + '.';
story += ' <br/>She visited taverns far and wide searching for clues for the whereabouts of ' + person + ' until finally she met a(n) ' + adjective5 + ' bard by the name of ' + person2 + '.';
story += ' ' + person2 + ' had heard of the ' + adjective3 + ' and ' + adjective4 + ' ' + person + '.';
story += ' ' + person2 + ' took out a(n) ' + instrument + ' and began to play a tune.';
story += ' <br/>"You can find the person you seek by travelling through the ' + adjective6 + ' ' + place1 + '.';
story += ' But, watch out for the ' + adjective7 + ' ' + noun2 + ' for it will surely try to ' + verb2 + ' you!';
story += ' Once you make it through the ' + adjective6 + ' ' + place1 + ' you will arrive at the shrine of ' + pluralNoun2 + ' where you must sacrifice a(n) ' + noun4 + '."<br/>';
story += ' After hearing this tune (and it\'s lack of any sort of melody) the Dragonborn decided that this quest was not worth her time, and she decided to go back to being a(n) ' + occupation + '.';
document.write(story);